name: Build Extension

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run package

      - uses: actions/upload-artifact@v4
        with:
          name: sms-grades-chrome
          path: sms-grades-chrome.zip

      - uses: actions/upload-artifact@v4
        with:
          name: sms-grades-firefox
          path: sms-grades-firefox.zip
